image: google/cloud-sdk:slim

stages:
  - deploy

variables:
  GCP_PROJECT_ID: "devplayground"
  GCP_REGION: "us-central1"
  SERVICE_NAME: "cloudrun-deploy-gitlabci"
  ARTIFACT_REPO: "cloudrun-cicd-images"
  IMAGE_NAME: "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REPO/$SERVICE_NAME"
  ENTRY_POINT: "gcpFunctionTesteCICD"
  ENV_FILE: "./env.json"
  SERVICE_ACCOUNT: ""

deploy-cloud-run:
  stage: deploy
  when: manual
  script:
    # Cria arquivo temporário da chave de serviço a partir da variável
    - echo "$GCP_SERVICE_KEY" > /tmp/key.json

    # Autentica com a chave de serviço
    - gcloud auth activate-service-account --key-file=/tmp/key.json
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud config set run/region $GCP_REGION

    # Build da imagem e push para Container Registry (ou Artifact Registry)
    - gcloud builds submit --tag $IMAGE_NAME .

    # Deploy da função
    - |
        gcloud functions deploy $SERVICE_NAME \
          --project=$GCP_PROJECT_ID \
          --runtime=nodejs22 \
          --trigger-http \
          --region=$GCP_REGION \
          --source=. \
          --entry-point=$ENTRY_POINT \
          --env-vars-file=$ENV_FILE \
          --service-account=$SERVICE_ACCOUNT

    # Remove o arquivo temporário
    - rm -f /tmp/key.json
